#parametrs
WIDTH, HEIGHT = 1000, 980
FPS = 60
ADD_OBSTACLES_TIMER = 150
INVINCIBLE_TIMER = 100
PLANE_SPEED = 5
OBSTACLE_SPEED = 7
COLUMNS = 10
OBSTACLE_SIZE = 50
MAX_OBSTACLE_SPEED = 25
MIN_BONUS_TIME = 300
MAX_BONUS_TIME = 500
BONUS_SPEED = 5
CLOUD_WARNING_TIME = 90
CLOUD_DURATION = 1000
CLOUD_SPEED = 3
CLOUD_SPAWN_MIN = 100
CLOUD_SPAWN_MAX = 300
MAX_PLANE_SPEED = 10
BOOST_SPEED_MULTIPLIER = 2.0
BOOST_MAX = 500
BOOST_DRAIN_RATE = 1.0
STEP_LEVEL = 100

#images 
PLANE_FILE = "resources/pngwing.com.png"
OBSTACLE_FILE = "resources/pngegg.png"
BACKGROUND_FILE = "resources/space2.jpg"
#BACKGROUND_FILE = "resources/start_screen_CZ.png" #EASTER EGG :D
#BACKGROUND_FILE = "resources/start_screen_RUS.png" #EASTER EGG 2 :D
GAMEOVER_FILE = "resources/game_over.png"
HEART_FILE = "resources/heart.png"
BONUS_FILE = "resources/bonus.png"